version: "3.3"
services:
  node:
    build: .
    ports:
      - "8080:8080"
    # links:
    #   - mongo
  # mongo:
  #     image: mongo:4.2
  #     ports:
  #         - "27017:27017"
  #     expose:
  #         - "27017-27019"
  #     volumes:
  #         - ./data:/data/db
