version: "3.3"
services:
  node:
    build: .
    volumes:
      - ./:/usr/src/app

    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    # volumes:
    #   - mysql_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
# volumes:
#   mysql_db:
